name: Infrastructure CI

on:
  pull_request:
    branches:
    - master

env:
  ARM_CLIENT_ID: 74036453-5cb8-403e-ae0e-0bb58f830a86
  ARM_CLIENT_SECRET: DV50_M53v2eBXVWU_6yBa~r6.7iZX-Ml1l
  ARM_SUBSCRIPTION_ID: b4820e67-c508-44af-a339-909558456352
  ARM_TENANT_ID: e4e01d27-a786-4129-bff4-bb3162c1772f
  TF_LOG: DEBUG

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./infrastructure
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        
      - name: Terraform Plan
        run: terraform plan