name: lint

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
      - 'web_client/**'

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_client
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          eslint_dir: web_client/
          prettier: true
          prettier_dir: web_client/
          auto_fix: true
