name: tests
on:
  push:
    paths:
      - 'web_client/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened]
jobs:
  coverage:
    name: Test & publish code coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_client
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
      - run: yarn install
      - run: yarn build
      - uses: paambaati/codeclimate-action@v2.6.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: yarn coverage
