name: ci

on:
  push:
    paths:
      - 'web_client/**'
  pull_request:
    types: [assigned, opened, synchronize, reopened]

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_client
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2-beta

      # ESLint and Prettier must be in `package.json`
      - name: Install Node.js dependencies
        run: yarn install

      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.github_token }}
          # Enable linters
          eslint: true
          eslint_dir: web_client/
          prettier: true
          prettier_dir: web_client/
          auto_fix: true
  test:
    name: Tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_client
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
      - run: yarn install
      - run: yarn build
      - run: yarn test:ci
  coverage:
    needs: [ test ]
    name: coverage
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web_client
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v2-beta
      - run: yarn install
      - run: yarn build
      - uses: paambaati/codeclimate-action@v2.2.4
        env:
          CC_TEST_REPORTER_ID: 6dc12ffb563215d618c598fd823f318f11d7655bcdd72a78fbb2ac5e48dfbb8e
        with:
          coverageCommand: yarn test:ci
          debug: true
